[build]
  base = "TamkeenAI_CareerSystem/frontend"
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# API proxy redirects
[[redirects]]
  from = "/api/*"
  to = "https://hessa-tamkeen-ai.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handling CORS preflight requests
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization" 