services:
  # Main Flask API (Port 5001)
  - type: web
    name: tamkeen-main-api
    env: python
    plan: free
    rootDir: TamkeenAI_CareerSystem
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader wordnet
    startCommand: cd backend && python -m gunicorn "app:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        value: mongodb+srv://loveanime200o0:R8tdEvgOvId5FEZv@tamkeen.0fmhury.mongodb.net/?retryWrites=true&w=majority&appName=Tamkeen&tlsAllowInvalidCertificates=true&tls=true
      - key: MONGO_DB
        value: tamkeen
      - key: USE_MOCK_DB
        value: true
      - key: OPENAI_API_KEY
        value: sk-myopenaiapikey
      - key: DEEPSEEK_API_KEY
        value: openai-route-deepseek-r1-free
      - key: HF_TOKEN
        value: hf_myhuggingfacetoken
      - key: PORT
        value: 5001
      - key: PYMONGO_TLS_INSECURE_SKIP_VERIFY
        value: true

  # Interview API (Port 5002)
  - type: web
    name: tamkeen-interview-api
    env: python
    plan: free
    rootDir: TamkeenAI_CareerSystem
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python simple_interview_api.py --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEEPSEEK_API_KEY
        value: openai-route-deepseek-r1-free
      - key: PORT
        value: 5002

  # Upload Server (Port 5004)
  - type: web
    name: tamkeen-upload-server
    env: python
    plan: free
    rootDir: TamkeenAI_CareerSystem
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader wordnet
    startCommand: cd backend && python simple_upload_server.py --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5004

  # Frontend app
  - type: static
    name: tamkeen-frontend
    env: static
    rootDir: TamkeenAI_CareerSystem/frontend
    buildCommand: npm install && npm run build
    publishDir: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://tamkeen-main-api.onrender.com
      - key: VITE_INTERVIEW_API_URL
        value: https://tamkeen-interview-api.onrender.com
      - key: VITE_UPLOAD_SERVER_URL
        value: https://tamkeen-upload-server.onrender.com
      - key: VITE_ENABLE_MOCK_DATA
        value: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 