services:
  # Main Flask API (Port 5001)
  - type: web
    name: tamkeen-main-api
    runtime: python
    plan: free
    buildCommand: cd TamkeenAI_CareerSystem && pip install -r requirements.txt && pip install nltk scikit-learn numpy==1.26.4 && python -c "import nltk; nltk.download('wordnet')"
    startCommand: cd TamkeenAI_CareerSystem/backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://loveanime200o0:R8tdEvgOvId5FEZv@tamkeen.0fmhury.mongodb.net/?retryWrites=true&w=majority&appName=Tamkeen&tlsAllowInvalidCertificates=true
      - key: MONGO_DB
        value: tamkeen
      - key: USE_MOCK_DB
        value: true
      - key: OPENAI_API_KEY
        value: sk-myopenaiapikey
      - key: DEEPSEEK_API_KEY
        value: openai-route-deepseek-r1-free
      - key: HF_TOKEN
        value: hf_myhuggingfacetoken
      - key: PORT
        value: 5001
      - key: PYMONGO_TLS_INSECURE_SKIP_VERIFY
        value: true
      - key: TLS_CERT_PATH
        value: system
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
      - key: MONGO_TLS
        value: CERT_NONE

  # Interview API (Port 5002)
  - type: web
    name: tamkeen-interview-api
    runtime: python
    plan: free
    buildCommand: cd TamkeenAI_CareerSystem && pip install -r requirements.txt && pip install nltk scikit-learn numpy==1.26.4 && python -c "import nltk; nltk.download('wordnet')"
    startCommand: cd TamkeenAI_CareerSystem/backend && gunicorn simple_interview_api:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://loveanime200o0:R8tdEvgOvId5FEZv@tamkeen.0fmhury.mongodb.net/?retryWrites=true&w=majority&appName=Tamkeen&tlsAllowInvalidCertificates=true
      - key: MONGO_DB
        value: tamkeen
      - key: USE_MOCK_DB
        value: true
      - key: OPENAI_API_KEY
        value: sk-myopenaiapikey
      - key: DEEPSEEK_API_KEY
        value: openai-route-deepseek-r1-free
      - key: HF_TOKEN
        value: hf_myhuggingfacetoken
      - key: PORT
        value: 5002
      - key: PYMONGO_TLS_INSECURE_SKIP_VERIFY
        value: true
      - key: TLS_CERT_PATH
        value: system
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
      - key: MONGO_TLS
        value: CERT_NONE

  # Upload Server (Port 5004)
  - type: web
    name: tamkeen-upload-server
    runtime: python
    plan: free
    buildCommand: cd TamkeenAI_CareerSystem && pip install -r requirements.txt && pip install nltk scikit-learn numpy==1.26.4 pdfplumber && python -c "import nltk; nltk.download('wordnet'); nltk.download('punkt'); nltk.download('stopwords'); nltk.download('averaged_perceptron_tagger')"
    startCommand: cd TamkeenAI_CareerSystem/backend && gunicorn "simple_upload_server:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://loveanime200o0:R8tdEvgOvId5FEZv@tamkeen.0fmhury.mongodb.net/?retryWrites=true&w=majority&appName=Tamkeen&tlsAllowInvalidCertificates=true
      - key: MONGO_DB
        value: tamkeen
      - key: USE_MOCK_DB
        value: true
      - key: OPENAI_API_KEY
        value: sk-myopenaiapikey
      - key: DEEPSEEK_API_KEY
        value: openai-route-deepseek-r1-free
      - key: HF_TOKEN
        value: hf_myhuggingfacetoken
      - key: PORT
        value: 5004
      - key: PYMONGO_TLS_INSECURE_SKIP_VERIFY
        value: true
      - key: TLS_CERT_PATH
        value: system
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
      - key: MONGO_TLS
        value: CERT_NONE