[build]
  command = "npm run netlify-build"
  publish = "dist"
  functions = "netlify/functions"

# Handle all OPTIONS preflight requests
[[redirects]]
  from = "/*"
  to = "https://tamkeen-main-api.onrender.com/:splat"
  status = 200
  force = true
  conditions = {method = ["OPTIONS"]}
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-auth-token", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# API proxy redirects for authentication
[[redirects]]
  from = "/api/auth/*"
  to = "https://tamkeen-main-api.onrender.com/api/auth/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-auth-token", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# API proxy redirects for general API
[[redirects]]
  from = "/api/*"
  to = "https://tamkeen-main-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-auth-token", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Special proxy for interview API
[[redirects]]
  from = "/interview-api/*"
  to = "https://tamkeen-interview-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-auth-token", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Special proxy for upload server
[[redirects]]
  from = "/upload-api/*"
  to = "https://tamkeen-upload-server.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-auth-token", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# Special proxy for prediction API
[[redirects]]
  from = "/predict-api/*"
  to = "https://tamkeen-predict-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-auth-token", Access-Control-Allow-Credentials = "true", Access-Control-Max-Age = "86400"}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Global headers for the site
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-auth-token"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400" 