[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# API proxy redirects
[[redirects]]
  from = "/tamkeen-api/*"
  to = "https://hessa-tamkeen-ai.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = ":origin", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization", Access-Control-Allow-Credentials = "true"}

[[redirects]]
  from = "/api/*"
  to = "https://hessa-tamkeen-ai.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = ":origin", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization", Access-Control-Allow-Credentials = "true"}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Handling CORS preflight requests
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = ":origin"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true" 