services:
  - type: web
    name: tamkeen-frontend
    env: node
    buildCommand: ./render-build.sh
    startCommand: node server.js
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    healthCheckPath: /api/health-check
    healthCheckTimeout: 5000
    envVars:
      - key: VITE_API_URL
        value: https://tamkeen-main-api.onrender.com # Update with your actual backend URL
      - key: VITE_INTERVIEW_API_URL
        value: https://tamkeen-interview-api.onrender.com
      - key: VITE_PREDICT_API_URL
        value: https://tamkeen-predict-api.onrender.com
      - key: VITE_UPLOAD_SERVER_URL
        value: https://tamkeen-upload-server.onrender.com
      - key: VITE_USE_MOCK_DATA
        value: true
      - key: VITE_ENABLE_MOCK_DATA
        value: true
      - key: VITE_ENABLE_MOCK_FALLBACK
        value: true
      - key: VITE_ENABLE_BACKEND_CHECK
        value: false 