services:
  # Main Flask API (Port 5001)
  - type: web
    name: tamkeen-main-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && pip install gunicorn pymongo==4.12.0 pyjwt flask-jwt-extended huggingface_hub numpy==1.26.4 openai
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: tamkeen
      - key: USE_MOCK_DB
        value: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: 86400
      - key: PORT
        value: 5001

  # Frontend app
  - type: web
    name: tamkeen-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://tamkeen-main-api.onrender.com
      - key: VITE_INTERVIEW_API_URL
        value: https://tamkeen-interview-api.onrender.com
      - key: VITE_UPLOAD_SERVER_URL
        value: https://tamkeen-upload-server.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Interview API (Port 5002)
  - type: web
    name: tamkeen-interview-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && pip install flask flask-cors pymongo==4.12.0 requests
    startCommand: cd backend && python simple_interview_api.py --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: PORT
        value: 5002

  # Upload Server (Port 5004)
  - type: web
    name: tamkeen-upload-server
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && pip install flask flask-cors nltk scikit-learn numpy==1.26.4
    startCommand: cd backend && python simple_upload_server.py --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5004 